// <auto-generated />
using System;
using E_BangEmailWorker.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_BangEmailWorker.Migrations.Generator
{
    [DbContext(typeof(GeneratorDbContext))]
    partial class GeneratorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("E_BangEmailWorker.Database.AssemblyComponentEntity", b =>
                {
                    b.Property<int>("AssemblyComponentEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssemblyEntityTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssemblyTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ComponentValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("AssemblyComponentEntityId");

                    b.HasIndex("AssemblyEntityTypeId");

                    b.HasIndex("AssemblyTypeId");

                    b.HasIndex("ComponentName");

                    b.ToTable("AssemblyComponentEntities", (string)null);
                });

            modelBuilder.Entity("E_BangEmailWorker.Database.AssemblyEntityType", b =>
                {
                    b.Property<int>("AssemblyEntityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssemblyEntityTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("AssemblyEntityTypeId");

                    b.HasIndex("AssemblyEntityTypeName");

                    b.ToTable("AssemblyEntityTypes", (string)null);
                });

            modelBuilder.Entity("E_BangEmailWorker.Database.AssemblyParametersEntity", b =>
                {
                    b.Property<int>("AssemblyParametersEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssemblyEntityTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssemblyTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityParametersName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityParametersValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("AssemblyParametersEntityId");

                    b.HasIndex("AssemblyEntityTypeId");

                    b.HasIndex("AssemblyTypeId");

                    b.HasIndex("EntityParametersName");

                    b.ToTable("AssemblyParametersEntities", (string)null);
                });

            modelBuilder.Entity("E_BangEmailWorker.Database.AssemblyType", b =>
                {
                    b.Property<int>("AssemblyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssemblyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("AssemblyTypeId");

                    b.HasIndex("AssemblyName");

                    b.ToTable("AssemblyTypes", (string)null);
                });

            modelBuilder.Entity("E_BangEmailWorker.Database.EmailRender", b =>
                {
                    b.Property<int>("EmailRenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodyComponenetsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodyParametersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmailRenderStrategyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmailTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FooterComponenetsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FooterParametersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeaderComponenetsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeaderParametersId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("EmailRenderId");

                    b.HasIndex("BodyComponenetsId");

                    b.HasIndex("BodyParametersId");

                    b.HasIndex("EmailRenderStrategyId");

                    b.HasIndex("EmailTypeId");

                    b.HasIndex("FooterComponenetsId");

                    b.HasIndex("FooterParametersId");

                    b.HasIndex("HeaderComponenetsId");

                    b.HasIndex("HeaderParametersId");

                    b.ToTable("EmailRenders", (string)null);
                });

            modelBuilder.Entity("E_BangEmailWorker.Database.EmailType", b =>
                {
                    b.Property<int>("EmailTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("EmailTypeId");

                    b.HasIndex("EmailTypeName");

                    b.ToTable("EmailTypes", (string)null);
                });

            modelBuilder.Entity("E_BangEmailWorker.Database.RenderStrategy", b =>
                {
                    b.Property<int>("RenderStrategyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssemblyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("RenderStrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("RenderStrategyId");

                    b.HasIndex("RenderStrategyName");

                    b.ToTable("RenderStrategies", (string)null);
                });

            modelBuilder.Entity("E_BangEmailWorker.Database.AssemblyComponentEntity", b =>
                {
                    b.HasOne("E_BangEmailWorker.Database.AssemblyEntityType", "AssemblyEntityType")
                        .WithMany("AssemblyComponentEntities")
                        .HasForeignKey("AssemblyEntityTypeId")
                        .IsRequired();

                    b.HasOne("E_BangEmailWorker.Database.AssemblyType", "AssemblyType")
                        .WithMany("AssemblyComponentEntities")
                        .HasForeignKey("AssemblyTypeId")
                        .IsRequired();

                    b.Navigation("AssemblyEntityType");

                    b.Navigation("AssemblyType");
                });

            modelBuilder.Entity("E_BangEmailWorker.Database.AssemblyParametersEntity", b =>
                {
                    b.HasOne("E_BangEmailWorker.Database.AssemblyEntityType", "AssemblyEntityType")
                        .WithMany("AssemblyParameterEntities")
                        .HasForeignKey("AssemblyEntityTypeId")
                        .IsRequired();

                    b.HasOne("E_BangEmailWorker.Database.AssemblyType", "AssemblyType")
                        .WithMany("AssemblyParametersEntities")
                        .HasForeignKey("AssemblyTypeId")
                        .IsRequired();

                    b.Navigation("AssemblyEntityType");

                    b.Navigation("AssemblyType");
                });

            modelBuilder.Entity("E_BangEmailWorker.Database.EmailRender", b =>
                {
                    b.HasOne("E_BangEmailWorker.Database.AssemblyComponentEntity", "BodyComponenets")
                        .WithMany("BodyComponents")
                        .HasForeignKey("BodyComponenetsId")
                        .IsRequired();

                    b.HasOne("E_BangEmailWorker.Database.AssemblyParametersEntity", "BodyParameters")
                        .WithMany("BodyParameters")
                        .HasForeignKey("BodyParametersId")
                        .IsRequired();

                    b.HasOne("E_BangEmailWorker.Database.RenderStrategy", "RenderStrategy")
                        .WithMany("EmailRenders")
                        .HasForeignKey("EmailRenderStrategyId")
                        .IsRequired();

                    b.HasOne("E_BangEmailWorker.Database.EmailType", "EmailType")
                        .WithMany("EmailRenders")
                        .HasForeignKey("EmailTypeId")
                        .IsRequired();

                    b.HasOne("E_BangEmailWorker.Database.AssemblyComponentEntity", "FooterComponenets")
                        .WithMany("FooterComponents")
                        .HasForeignKey("FooterComponenetsId")
                        .IsRequired();

                    b.HasOne("E_BangEmailWorker.Database.AssemblyParametersEntity", "FooterParameters")
                        .WithMany("FooterParameters")
                        .HasForeignKey("FooterParametersId")
                        .IsRequired();

                    b.HasOne("E_BangEmailWorker.Database.AssemblyComponentEntity", "HeaderComponenets")
                        .WithMany("HeaderComponents")
                        .HasForeignKey("HeaderComponenetsId")
                        .IsRequired();

                    b.HasOne("E_BangEmailWorker.Database.AssemblyParametersEntity", "HeaderParameters")
                        .WithMany("HeaderParameters")
                        .HasForeignKey("HeaderParametersId")
                        .IsRequired();

                    b.Navigation("BodyComponenets");

                    b.Navigation("BodyParameters");

                    b.Navigation("EmailType");

                    b.Navigation("FooterComponenets");

                    b.Navigation("FooterParameters");

                    b.Navigation("HeaderComponenets");

                    b.Navigation("HeaderParameters");

                    b.Navigation("RenderStrategy");
                });

            modelBuilder.Entity("E_BangEmailWorker.Database.AssemblyComponentEntity", b =>
                {
                    b.Navigation("BodyComponents");

                    b.Navigation("FooterComponents");

                    b.Navigation("HeaderComponents");
                });

            modelBuilder.Entity("E_BangEmailWorker.Database.AssemblyEntityType", b =>
                {
                    b.Navigation("AssemblyComponentEntities");

                    b.Navigation("AssemblyParameterEntities");
                });

            modelBuilder.Entity("E_BangEmailWorker.Database.AssemblyParametersEntity", b =>
                {
                    b.Navigation("BodyParameters");

                    b.Navigation("FooterParameters");

                    b.Navigation("HeaderParameters");
                });

            modelBuilder.Entity("E_BangEmailWorker.Database.AssemblyType", b =>
                {
                    b.Navigation("AssemblyComponentEntities");

                    b.Navigation("AssemblyParametersEntities");
                });

            modelBuilder.Entity("E_BangEmailWorker.Database.EmailType", b =>
                {
                    b.Navigation("EmailRenders");
                });

            modelBuilder.Entity("E_BangEmailWorker.Database.RenderStrategy", b =>
                {
                    b.Navigation("EmailRenders");
                });
#pragma warning restore 612, 618
        }
    }
}
