services:
  adminer:
    image: adminer
    restart: no
    ports:
      - "8080:8080"
    networks:
      - postgresnet

  db:
    image: postgres
    restart: no
    environment:
      POSTGRES_PASSWORD: dockersql
    ports:
      - "5432:5432"
    networks:
      - postgresnet

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: no
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - postgresnet

networks:
  postgresnet:
